### ISSUE TITLE
Order quantity issue

### ISSUE THREAD

**Issue by trydis** [sonvister/Binance#109]
I'm fetching the order history using `GetOrdersAsync` and for a given order it returns `2.00000000` (example value) for `ExecutedQuantity`. I use this value for placing a stop loss limit order.

I get the following exception:
```
Binance.BinanceHttpException: [BadRequest]: 'Bad Request' - Account has insufficient balance for requested action. (-2010)
```

Checked on the website and the quantity is actually `1.98434000`.

So my question is how, if possible, can I get the exact quantity, to be able to place the order?

**Comment by sonvister** [comment]
@trydis, you will have better luck getting an answer to this type of question from the official Binance API Telegram (https://t.me/binance_api_english).

My first thought is that the quantity is different because of fees.... Perhaps if you use BNB for fees you will get expected quantities (*and cheaper fees*) .

Let me/us know what you find out and if I need to add/correct something with this unofficial C# API library to get the information you need.

**Comment by sonvister** [comment]
FYI, `GetOrdersAsync` uses [`/api/v3/allOrders`](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#all-orders-user_data).

**Comment by trydis** [comment]
Thanks, I'll try my luck there. I'm using BNB for fees and it worked as expected on another order, weirdness.

I'll do some digging. Also, I guess another way would be to get the balance and use that value.

**Comment by sonvister** [comment]
@trydis, glad that you are headed in the right direction. Seems like getting the balance (*or sticking with BNB for fees*) would be the most reliable solution (*rather than calculating fees*). Feel free to add more information, if you think it might be helpful to others.
