### ISSUE TITLE
missing symbols in latest available version

### ISSUE THREAD

**Issue by pavlexander** [sonvister/Binance#11]
Latest available version in nuget is 0.2.0-alpha.8. However, it seems to me missing some of the new symbols in API. On the other hand, the source code in Git already contains new codes. For example:
`public static readonly Symbol NAV_BTC`

Is it possible to upgrade to latest available version (trunc) somehow locally?
What is the build cycle of this project and how often when can we expect to get updates, even in Alpha releases?

In the example above, I'd like to have support for **NAV_BTC**. I would to appreciate to hear any advices on how to add support for it locally when there is no latest build available..

Thanks.

**Comment by sonvister** [comment]
Binance is always adding new symbols. While I try to keep the static Assets and Symbols up-to-date, I do not plan to release a new version of this library every time there is a new symbol. I provide the static Assets and Symbols "for convenience/reference only." If you wish to have a full list of current Symbols at run-time you can use the `IBianceApi.GetSymbolsAsync()` method. Also, there is the static `Symbol.Cache` (initialized with the static Symbols) that you can reference and keep up-to-date with `Symbol.UpdateCache()`.

Currently, I use the master branch for development and at times it will have code that is not yet released. If you wish to see the source code that applies to a specific release, you can select the corresponding **Tag** for that version.

If you want to build the latest development version, you can use **Visual Studio Community 2017**. You can then build/publish a NuGet package with the latest source and reference your local package source in your application. You may want to give that local package build a different name or versioning to avoid conflicts with future upgrades. If I do not have the latest Symbols in source you can use the `BinanceCodeGenerator` sample application to update the `Asset.cs` and `Symbol.cs` files. Otherwise, you can also create any static Symbol manually in the Binance library or you application code.
