### ISSUE TITLE
Having Issues I Can'

### ISSUE THREAD

**Issue by khoofard** [sonvister/Binance#110]
Me again. This is a question I think. Not necessarily an issue. Hopefully these aren't "noob"'ish questions.

I've attached the results from my immediate window after a 90 minute run with my bot. My bot is written in vb.net and any run over an hour I get messages like you see. I'm guessing I have a keep alive issue but I cannot tell since I get a lot of socket disposed messages. Does KeepALive only work for HTTP connections or is it need for Socket connections as well?

Is there a simple way to turn on the loggers inside your code? I see them in there. But I cannot see how to use them. Probably my deficiency in C#.

**Comment by khoofard** [comment]
[ImmediateWindow.txt](https://github.com/sonvister/Binance/files/2635838/ImmediateWindow.txt)

**Comment by khoofard** [comment]
Further testing shows this to happen at around the 45 minute mark. So clearly it seems like something is expiring or timing out.

**Comment by sonvister** [comment]
@khoofard, this library uses `Microsoft.Extensions.Logging`. You can reference the sample applications to see how that is configured. The `Binance.Application` library includes the file logger extension.

In general, I do not debug user application code, particularly not network related issues, and especially not VB. Otherwise, good luck and please let me know if you find an issue with the code.

**Comment by khoofard** [comment]
I wasn't expecting you to debug anything. I was hoping you could shed some light on maybe where those messages could be originating from based on your own experience.

I have looked at the samples before and will re-visit them again. Thank you for your response.
