### ISSUE TITLE
GetSymbolsAsync fails

### ISSUE THREAD

**Issue by bobby-ko** [sonvister/Binance#111]
GetExchangeInfoAsync is responding with a new JSON structure - more entries in the "filters" array. Method fails trying to get LOT_SIZE properties because its not at index 1 any more.

I've got a  fix for this already, do you guys accept push requests?

**Comment by sonvister** [comment]
@bobby-coinstorm, thanks for mentioning this issue. I have been working on other changes so I started looking into this too. I would be interested in seeing your fix (*btw, there are no "guys", it's just me*).

So far I have found this to be significantly more than just changing indexes since they also broke the existing "PRICE_FILTER" by not including the actual values. I have a potential fix to keep the related validation working, but there are aspects that are probably unfinished or incorrect and certainly not to my liking. Regardless, there is probably no rush to release this since it has apparently been broken since 11-13....

**Comment by bobby-ko** [comment]
Thanks for the quick response on this. My "fix" is very to what you have - actually you seem to handle the case even better so I'm going to use that in my tests for now until the package update is out. So far so good, I'll let you know if I find any issues.

**Comment by sonvister** [comment]
@bobby-coinstorm, let me know if you find any issues with **0.2.0-beta9**. Thanks.
