### ISSUE TITLE
PriceRange issue

### ISSUE THREAD

**Issue by evo11x** [sonvister/Binance#115]
In the latest binance api, PriceRange.GetLowerValidValue, PriceRange.GetUpperValidValue and GetValidValue returns zero. (Tested with Theta at price 0.00001334) ...GetLowerValidValue(0.00001334)=0

**Comment by sonvister** [comment]
@evo11x, are you updating the symbols at run-time (*the static symbols no longer work with price validation*)?

From 0.2.0-beta9 release notes: 
"[BREAKING: Because of this change, validation will not work until symbols are updated at run-time.](https://github.com/sonvister/Binance/releases/tag/v0.2.0-beta9)"

**Comment by evo11x** [comment]
Oh I see, and how can I update symbols at runtime?

**Comment by sonvister** [comment]
https://github.com/sonvister/Binance/wiki#assets-and-symbols

**Comment by evo11x** [comment]
Thanks now it works! So now I must call Symbol.UpdateCacheAsync(api); at least at every app startup.
This is good because the static file symbols update was not very convenient.

**Comment by sonvister** [comment]
Yes, as recommended: https://github.com/sonvister/Binance/wiki#update-frequency
