### ISSUE TITLE
Orderupdate vs Tradeupdate

### ISSUE THREAD

**Issue by wireless90** [sonvister/Binance#118]
Hi im using the userdatawebsocket manager and subscribed to the orderupdate event. 

I put a breakpoint at its callback and it fires when i set a new order. The order.status is eq to New.  

So i was waiting for it to fire again when that order gets filled. But it does not fire.

Also what is the diff between orderupdate and tradeupdate. Can I use tradeupdate to check if an order is filled?

**Comment by sonvister** [comment]
@wireless90, continuing the discussion from issue (#117)...

From the [source code](https://github.com/sonvister/Binance/blob/master/src/Binance/Client/UserDataClient.cs#L260), the `TradeUpdate` event is fired when the [web API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#order-update) event type is "executionReport" and the execution type is "TRADE". The `AccountTradeUpdateEventArgs` includes both the `Order` and `Trade` information. All other "executionReport" execution types fire the `OrderUpdate` event with just the `Order` information.

From the [web API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#order-update) (since there is no "COMPLETE" or "FILLED" execution type), you should be able to determine when an order is filled from the `TradeUpdate` event by looking at the [`Order.Status`](https://github.com/sonvister/Binance/blob/master/src/Binance/Account/Orders/OrderStatus.cs) = `Filled` vs. `PartiallyFilled`.

**Comment by sonvister** [comment]
@wireless90, I am curious, did you register using my referral ID (10899093)?

**Comment by wireless90** [comment]
> @wireless90, I am curious, did you register using my referral ID (10899093)?
Sorry @sonvister , already had my binance account a year ago.

**Comment by sonvister** [comment]
Regarding use of referral ID, I imagine that is the case with a lot of users of this library. But, I also wonder if anyone considers creating new accounts or perhaps contacting Binance after the fact (*I suspect they might still make the update post account creation*).
