### ISSUE TITLE
Combined Streams

### ISSUE THREAD

**Issue by markgould** [sonvister/Binance#19]
Do you have plans to support combined streams? Details here https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

I could look into adding this and submit a PR if you'd like.

**Comment by sonvister** [comment]
@markgould I added support for combined streams (*code only*). I want to test the changes further and update some documentation (and finish some TODOs) before the next release, but I'd like to hear if you have any comments/suggestions on what I've done so far. Thanks.

**Comment by markgould** [comment]
At first glance, I like it. I would be happy to pull the code down and do a local build to test it out too.

Is there any notification when the stream is closed at the 24 hour mark? I think from what I can see I can access the underlying IWebSocketClient and then use the close event. Is it worth trying to add some of the reconnect logic in the library or is that better left to the consumer?

**Comment by sonvister** [comment]
@markgould you are most welcome to try it out... I, and probably everyone else, would appreciate any issues being found sooner rather than later.

I have not tested the 24-hour disconnect yet. If there is some specific indication that this 'normal' disconnect has occurred as opposed to a disconnect for any other reason I could see the possibility of adding some reconnect logic to one of the higher level WebSocket classes for convenience. Otherwise, I'd rather leave that control and decision making to the consumer/application.

Currently, for notification of disconnect, there is the `IWebSocketClient.Close` event (*as mentioned*) and also the completion of the `IWebSocketStream.StreamAsync()` task, which occurs after the `Close` event. Also, the closest thing to *built-in* reconnect is `RetryTaskController`.

**Comment by sonvister** [comment]
Another thought, perhaps a 24-hour timer could be used to preempt the 24-hour disconnect to do a planned reconnect. But, the flow of data will still be interrupted. If the consumer can react to and handle breaks in data (*not dependent upon an open stream being a contiguous stream*) then perhaps it could work...

But, on second thought, I don't see what would be gained from this since the consumer would still need to handle unexpected disconnects or potential non-contiguous data likely resulting in a reconnect of their own anyway.

**Comment by sonvister** [comment]
@markgould, I believe the combined streams feature is 'done' (*I hope you've found it useful*). I did end up adding reconnect logic by extending `RetryTaskController`.... Let me know if you have anything to add (*anything not working or missing or can this can be closed*).
