### ISSUE TITLE
Sample application throws timestamp error

### ISSUE THREAD

**Issue by mmartain** [sonvister/Binance#2]
account
! Exception: [BadRequest]: 'Bad Request' - Timestamp for this request is not valid. (-1021)

Should i enter a timezone somewhere? I entered my API keys in the setttings file succesfully.

**Comment by sonvister** [comment]
There is no need for timezone information, the generated timestamps are Unix time (milliseconds).

I have **not been able to reproduce** your error with the latest code in DEBUG and RELEASE with my API keys in the appsettings.json file. I suspect your issue was temporary or at worst intermittent. Please let me know if the error persists.

The internal timestamp offset is meant to help synchronize your system time with the Binance server time. It's plausible your system time (and the generated timestamps with the offset) was greater than the Binance server time causing the error. I noticed in the latest [API documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) that the Binance timing security logic now has a "+ 1000" milliseconds. That change should help if this was/is happening.

**Comment by sonvister** [comment]
In version 0.2.0-alpha.3 I have adjusted the timestamp offset calculation to use averaging, which should help avoid invalid timestamps. Again, please let me know if the error persists.
