### ISSUE TITLE
Please include wrapper for endpoint "/api/v1/exchangeInfo"

### ISSUE THREAD

**Issue by tipa** [sonvister/Binance#21]
Interested in this because of the rate limits especially.
Maybe theres even a way to optionally block further requests when a rate limit is exceeded to prevent ip bans.

**Comment by sonvister** [comment]
@tipa, I've considered creating a *high-level* wrapper for the exchange info (for *low-level* JSON use `IBinanceHttpClient.GetExchangeInfoAsync`) to get the current rate limits (everything else is in `Symbol`). But, I don't see that as a high priority since the existing exchange rate limits have yet to change and if they do change the rate limiter can be adjusted with `BinanceApiOptions`.

The rate limiter is there to prevent rate limit exceptions and subsequently IP bans. If it is not providing this feature (*timing may be too close*), then it needs to be adjusted with `BinanceApiOptions` (or further adjusted internally by a small % if it *is* too close). If you are getting rate limit exceptions, you can prevent being IP banned by delaying calls at the application level. I'll look into what it would take to adjust the rate limiter at run-time if the exceptions occur, but the first priority is to prevent the exceptions in the first place.

In addition to the configurable rate limit counts and durations, each API method has a 'weight' factor (*typically 1*), which is applied to the count and is currently hard-coded. It would help to know if any particular methods are causing exceptions in case the weight factors need to be changed.

*UPDATE: 0.2.0-alpha.13 will include the modified (1/14) request rate weights.*

**Comment by raphaotten** [comment]
Can you make a quick example how to add a rateLimiter to the Api?
The Api.HttpClient.RateLimiter is readOnly. But adding it in the constructor is not straightforward for me either. Using a ServiceCollection as in the sample also doesn't seem to work for me for a Windows Forms project :-/

**Comment by spbsmile** [comment]
@raphaotten  you can see on this
[source of Kraken bitcoin exchange API](https://github.com/discosultan/KrakenCore/blob/master/src/KrakenClient.cs#L257)

**Comment by raphaotten** [comment]
Thank you. I meant right in the beginning, when creating the API
`Api = new BinanceApi();`
now 
`Api.HttpClient.RateLimiter = myRateLimiter; `
is not possible, as it's read only. So I need to add the binanceHttpClient in the BinanceApi(myBinanceHttpClient) constructor.
But for that I need an instance of BinanceHttpClient. But it has only an internal constructor so I can't just do
`BinanceHttpClient binanceHttpClient = new BinanceHttpClient();`

That's where I'm stuck.

**Comment by sonvister** [comment]
@raphaotten I made the `RateLimiter` property read/write. There is also a `RateLimiter` associated with the `BinanceApiUser` which was already read/write (*now they are consistent*).
