### ISSUE TITLE
[Question] Serializing an OrderBook to JSON?

### ISSUE THREAD

**Issue by Pursche** [sonvister/Binance#22]
Hi, I am using your Binance library to make a tool for simulations and graphs, my program is split in two. One part mines data in realtime with a specific interval and duration, then when it's done it serializes it to JSON and saves it to disc. I can then run the second part of the program which reads one of my many saved datafiles, deserializes it back into a list of OrderBooks and runs some analysis and simulations on them. I do realize that I can get historic data directly from Binance but I would prefer to do it through regular GetOrderBookAsync because of the control it gives me.

Serializing the OrderBook works without any problems, but deserializing it is proving a bit troublesome.

The first error I encountered was this: Newtonsoft.Json.JsonSerializationException: 
'Unable to find a constructor to use for type Binance.Market.OrderBookTop. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'orderbook.Top.Symbol', line 16, position 23.'

I solved this one by adding the [JsonConstructor] attribute to this constructor:
public OrderBookTop(string symbol, decimal bidPrice, decimal bidQuantity, decimal askPrice, decimal askQuantity)

This solved that error but gives me an even more troublesome issue.

In this constructor of OrderBook: public OrderBook(string symbol, long lastUpdateId, IEnumerable<(decimal, decimal)> bids, IEnumerable<(decimal, decimal)> asks)
I get the following error: System.ArgumentException: 'An entry with the same key already exists.'
On this line: _bids.Add(bid.Item1, new OrderBookPriceLevel(bid.Item1, bid.Item2));

When looking inside of the "bids" array all the entries are "0, 0" in price and quantity.
I have absolutely no idea how to solve this, which leads me to my question.
Have you managed to serialize an OrderBook before? Do you have an example of how to do that?

Here is a minimal example of how to reproduce the issue: https://pastebin.com/FMceXnLj

**Comment by Nucs** [comment]
Would be nice to have all POCOs like OrderBook support Newtonsoft.Json serialization.

**Comment by sonvister** [comment]
@Pursche I created `OrderBookJsonConverter` to serialize and deserialize the `OrderBook` and `SerializationExample` to demonstrate its usage. Let me know if this works for you.

@Nucs `OrderBook` is not a POCO, it is an immutable domain (value) object. Regardless, what other classes do you have in mind that do not work with `JsonConvert.SerializeObject()` and `JsonConvert.DeserializeObject<Type>()` that could use a `JsonConverter`?

**Comment by Pursche** [comment]
@sonvister That worked perfectly, thank you very much for a quick response! :D

**Comment by Nucs** [comment]
@sonvister I haven't checked in depth what works and what doesn't but the idea is to make server's responses serializable for later on simulation.
Classes like `AggregateTrade`, `SymbolStatistics`, `Order` and so on.

**Comment by sonvister** [comment]
@Nucs and @Pursche I'll see if I can add that capability to the `Order` class (others I have verified with unit tests).

Also, I didn't see this yesterday, but the use case you both describe was a primary reason for the initial dual-layer API design (`IBinanceApi` and `IBinanceJsonApi`), which I now realize I lost when I created `IBinananceHttpClient`.

The purpose of `IBinanceApi` was and is deserialization of JSON. The purpose of `IBinanceJsonApi` was to provide an interface for `IBinanceApi` that returned JSON (*HTTP or otherwise*). You could then use the default `IBinanceJsonApi` implementation (*HTTP*) and save JSON. Then pass a custom `IBinanceJsonApi` that accesses your JSON store to `IBinanceApi`. The application layer could then always use `IBinanceApi` regardless of the the data source.

So, my plan now is to recreate the `IBinanceJsonApi` interface as a layer between `IBinanceApi` and `IBinanceHttpClient`.

**Comment by sonvister** [comment]
So, instead of `IBinanceJsonApi` I am going with serialization abstractions for each value object beginning with `OrderBook`. I am using the existing `OrderBookJsonConverter`, but @Pursche, this changes the JSON output of the converter to lower instead of upper title case to be consistent with Binance JSON (*including the 'symbol' property in JSON output is now optional with a new flag*).

My thinking...

`IBinanceJsonApi` would create a more complicated interface for just deserialization of JSON data, with implementations likely having several unimplemented methods. Also, things like rate limiting don't make sense for other low-level implementations (sharing an abstraction with `IBinanceHttpClient`). The primary motivation is to eliminate the unnecessary deserialize/serialize processing step for the use case mentioned.

The serializers would be used with other implementations processing JSON (*from a data store*) instead of those implementations being injected into `BinanceApi`. I envision creating other interchangeable 'provider' interfaces to implement (and `IBinanceApi` will extend). So, @Pursche, you should be able to simplify some code and processing with `OrderBookSerializer` and `IBinanceHttpClient` if the common JSON format is acceptable.

The serializers can be altered/extended to detect different JSON formats, but my implemenations will likely just support Binance JSON format (in/out). The serializers (when injected into `BinanceApi`) will also allow for application level corrections to any deserialization issues... for instance, if JSON is changed by Binance before the library can be updated/fixed.
