### ISSUE TITLE
Buy And Sell Fee Calculates.

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#26]
Greetings;
I felt I needed to consult you on a problem.
My problem is that way. when I have a purchase or sale transaction, I have them on a bond basis.
For example, I get 3 USDT money and I get BTC at 11200.00. I have to get 0.00026786 BTC according to the calculation. but when we add Fee to the account, this amount is even lower. Now let's face it.
I record this when I register it in the database, but when the feeler on the binance side is deducted, the purchase BTC amount is lower. When I sell it, it is not the real value of binance but it opens my sales order. in this case sometimes it is likely that the rest of the body is taking it. This is affecting my other purchases. I am getting insufficient funds in my purchases awaiting sale as the balance is getting low.
Do we have a relevant area for buying and selling, for example?
I would like to make the purchase and sale stabilize in this way, indicating how much real amount I will get in the amount of USDT I want to buy and the actual value of the current coin I am going to buy. Is there a feature that we can use in this way?
If not, is it possible to add it? If you can not add or wait, do you have a temporary solution to me until this time?
I am using C # Windows Forms.
Thank you very much for your interest.

I did not find your donation links.
Could you please share your donation links?
I am using such a large amount of labor. And as a casualty, I would like to make a contribution to you. As much as I can
.
Best regards...

**Comment by Nucs** [comment]
A tl;dr version: 
* A high-level way to translate `x btc` to `x usdt` and the other way around. That is verified and tested.
* A fees calculator.
so that way you'll be able to calculate fees the proper way.

(Lemme know if it is inaccurate)

I must agree, adding a high level currency translator can be very useful.
Even I planned to write one down myself.

**Comment by sonvister** [comment]
@turgayacar, thanks for the offer, I have added donation addresses for various assets to README.md (let me know if you had something else in mind). One option that won't eliminate fees, but would keep fees from affecting your USDT and BTC asset balances is using [BNB for fees](https://support.binance.com/hc/en-us/articles/115000583311) (*and save 50%*).

@Nucs, the currency/asset price translation and fee calculator features might be something I do later, but at the moment I consider them *out-of-scope* of the project with the primary goal being to provide data rather than do calculations on that data. I envision something like that at a higher level (part of another library perhaps) that can utilize multiple exchange APIs. That said, I may change my mind as it is very useful and may spark my interest one of these days...

Considering what is available, if I were to estimate fees *pre-trade* I might start with polling `GetPriceAsync` or `GetPricesAsync` or keep real-time price information with `ISymbolStatisticsWebSocketClient` or `ISymbolStatisticsCache` and reference `AccountCommissions` properties. This would only be an estimate since those values are always changing and may not reflect what is used by Binance to calculate fees when the trade is executed. I think the best/only information for *post-trade* calculations is `AccountTrade.Commission` and `AccountTrade.CommissionAsset`.

Hope this helps.

*UPDATE*: I am adding a method to `ISymbolStatisticsCache` to return multiple symbols in one call (*see below*). Binance pushes updates every second, with internal locking, statistics queried with this method will be from the same update. As for calculating conversion ratios, I do not know if Binance uses `LastPrice` or mid-market price: (`BidPrice` + `AskPrice`) / 2.

```C#
IEnumerable<SymbolStatistics> GetStatistics(params string[] symbols);
```

**Comment by Nucs** [comment]
Great news, that will come very handy.
Something worth mentioning; if anyone plans to build currency converter:

If enabled, BNB Discount is calculated in the following manner: 
> 1. Converting logic of BNB market value.
> 
> If the trade receivable is NEO, we will calculate it by the exchange ratio of NEO to BNB at the market price,  which is based on the market price of  NEO / BTC and BNB / BTC.
> 
> Exchange ratio of NEO/BNB = NEO/BTC[market price] /(BNB/BTC [market price]). Binance update cycle for the market price is 1 second.  

Taken from [here](https://support.binance.com/hc/en-us/articles/115000583311).

**Comment by sonvister** [comment]
@Nucs and @turgayacar, I've also added support for **Fills** in `Order` returned from `IBinanceApi.PlaceAsync()` with low-level [`newOrderRespType`](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade) always set to 'FULL'. This could help with calculations when making MARKET orders since `Fill` includes the `Commission` (fee).
