### ISSUE TITLE
Reconnecting websocket

### ISSUE THREAD

**Issue by mirror222** [sonvister/Binance#28]
I noticed that the library will not connect automatically if the connection was closed by binance.
any advice would be highly appreciated :)

2018/01/22 10:54:48.089|INFO|The remote party closed the WebSocket connection without completing the close handshake. |Demo.Program|
2018/01/22 10:54:53.091|INFO|DepthWebSocketClient is already subscribed to symbol: "ETHUSDT" |Demo.Program|

**Comment by sonvister** [comment]
@mirror222, the issue of reconnect is discussed some in #19, but is not an existing feature since handling disconnect (normal or abnormal) is best left to the API consumer/controller. For similar reasons there is no embedded Thread. However, the library does provide the `RetryTaskController` for simple automatic reconnecting.

**Comment by sonvister** [comment]
@mirror222, I've made some changes with 0.2.0-alpha16 to improve reconnect behavior of the web socket clients and caches that should help. Also, the `BinanceMarketDepth` sample application demonstrates usage of `RetryTaskController` and how it can be used with or without combined streams.

**Comment by mirror222** [comment]
awesome!
