### ISSUE TITLE
Use ConcurrentQueue insted Queue in RateLimiter

### ISSUE THREAD

**Issue by nicolasesprit** [sonvister/Binance#29]
RateLimiter is not thread-safe. Enqueue or Dequeue can throw Exception "Source array was not long enough. Check srcIndex and length, and the array's lower bounds".

**Comment by sonvister** [comment]
Thanks @nicolasesprit for bringing that to my attention. I see I lost synchronization when I modified `RateLimiter` to support multiple counts with version 0.1.16.... This time I am going to apply the lock around the delay as well for simplicity and because it serves to serializes access just in a different way. I could use a ConcurrentQueue as a fix for that exception, but the rest of the rate limiter logic needs to be protected from multiple threads too else the calls to Enqueue and Dequeue could be out of sequence.
