### ISSUE TITLE
Real time order book out of sync

### ISSUE THREAD

**Issue by raphaotten** [sonvister/Binance#32]
Hi,

how can I tell if a realtime orderbook (https://github.com/sonvister/Binance/wiki/Realtime-Caching#order-book-cache) is out of sync?
The subscribed updates would not happen anymore and my app didn't notice.
How can I prevent this from happening in the future?

Thank you!

**Comment by sonvister** [comment]
@raphaotten, I suspect you mean how can your application tell, but *you* can tell what is happening by looking at logger output, which would be helpful here to know how to address this issue best.

Assuming the problem is the order book becoming out-of-sync, `OrderBookCache` will wait a second and query the latest order book with maximum limit (re-synchronize). If still out-of-sync will wait for the next update event (*probably less than a second*) and re-synchronize again. This will continue without sending new order book data until synchronized.

This higher-level implementation is meant to hide that situation from the application with the assumption that the application can't do anything other than wait and eventually there will be data. If there are issues getting data for whatever reason that process could potentially continue a while 🤷‍♂️ , but what else can be done...?

Perhaps I can add a flag for the application to identify if the cache is in the process of synchronization, but this would need to be polled regularly or when updates haven't happened in a while. Still the application will either wait or reset the cache/connection.

Perhaps, internally, if the cache re-synchronizes beyond x attempts in a row it can force the underlying web socket to close getting the attention of the application and forcing it to handle a disconnect.

Perhaps, the cache can provide a synchronizing event and the application can decide what to do when it receives the event (*typically it would do nothing unless updates weren't occurring also*). Maybe providing a re-synchronize count here or on the cache would be helpful.

Also, without making any library changes, the application could reset the web socket and/or cache on its own if new data is not received in a certain period of time.

**Comment by sonvister** [comment]
@raphaotten it would helpful to know if you are using the partial stream (limit > 0), where most of the last comment wouldn't be applicable since there isn't any synchronization done.

**Comment by raphaotten** [comment]
Thanks for your answer.
It seemed there were no updates at all anymore (for more than an hour, when I found out and restarted the application).
For AccountInfo I have a timestamp (of the last update?), that I check for.
Maybe this would help?!

```
private Dictionary<string, IOrderBookCache> orderBooksCaches = new Dictionary<string, IOrderBookCache>();

(...)

        async Task AddOrderBookToCache(string symbol)
        {
            if (!orderBooksCaches.ContainsKey(symbol))
            {
                orderBooksCaches.Add(symbol, serviceProvider.GetService<IOrderBookCache>());
            }
            orderBooksCancellations.Add(symbol, new CancellationTokenSource());
            orderBooksCaches[symbol].Update += OnOrderBookUpdateEvent; // optionally, subscribe to update events.
            var taskOrderBookCacheSubscription = Task.Run(() => orderBooksCaches[symbol].SubscribeAsync(symbol, evt =>
            {
                // optionally, use an inline event handler.
            }, orderBooksCancellations[symbol].Token)); // starts synchronization.
        }

```

**Comment by sonvister** [comment]
@raphaotten, I see you're not using the partial depth stream and you are maintaining multiple order books. Also, you're not using the latest version based on `SubscribeAsync`, which is now `StreamAsync`.

Recommendations:
- Upgrade to the latest version of the Binance library.
  - Remove unnecessary (empty) callback from the *now* `StreamAsync` method.
- Determine if partial depth stream (order book limit: 5, 10, 20) is sufficient for your application.
- Consider using a single application-wide web socket stream (combined streams).
- Help me better understand/debug the situation:
  - Provide logging information around when the error occurs.
  - Let me know which order books you are maintaining concurrently (*to reproduce*).

**Comment by sonvister** [comment]
@raphaotten I've *hopefully* made some improvements to `OrderBookCache` in **0.2.0-alpha18**. Some of the previously mentioned behavior has changed, but my recommendations stand if you are still having trouble. Please try the latest version and let me know....

**Comment by raphaotten** [comment]
I didn't have the problems again with the newer versions & streams!
Thank you!
