### ISSUE TITLE
Use a DateTimeOffset for the OpenTime and CloseTime in a candlestick object

### ISSUE THREAD

**Issue by Wtiben** [sonvister/Binance#35]

**Comment by sonvister** [comment]
@Wtiben, thanks for the suggestion. I might consider `DateTime` instead of `DateTimeOffset` for those `long` values. While I like `DateTimeOffset` when working with local times, these timestamps will always be UTC (*within the scope of the library*). Also, since `DateTime` has the `Kind` property it can be identified as UTC without the use of an offset. 

So, if I change the `Candlestick` properties to `DateTime` I would probably want to change all timestamps in the library accordingly to be consistent. At the moment, I'd rather go with an additional helper extension: `ToDateTime()` for long values (*assumed to be timestamps*).

**Comment by sonvister** [comment]
@Wtiben, I'll consider making the following properties `DateTime` types:

- `Candlestick.OpenTime`
- `Candlestick.CloseTime`
- `SymbolStatistics.OpenTime`
- `SymbolStatistics.CloseTime`
- `IChronological.Timestamp` *maybe... affects several classes.*

The `DateTime` properties would still serialize to `long` timestamps.

**Comment by sonvister** [comment]
@Wtiben, I decided I liked the idea of `DateTime` times instead of `long` timestamps for everything (*as tedious as it was to change*). Available soon in **0.2.0-alpha20**.
