### ISSUE TITLE
A question that into the mind.

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#40]
Greetings;
I want to get your views on a topic.
For example, I want to buy in a synchronous manner. In this, I remove the await tag and add .GetAwaiter (). GetResult () to the method end.
But when I do this, it does not come back to me even though it's done on the server side. I waited about 30 minutes to test, but there was no return. In some cases, asynchronous processing affects negatively. How should I follow a relevant path?
I also specify that the value of recwindow is 0.
how can I do these operations more quickly and synchronously? The advantage for my software being synchronous is that it may be waiting on acceptable values ​​that are not a problem waiting to happen. but I do and I do transactions with the time cycle and I chain transactions with each other. Automatic trading. If this is the case, asynchronous operations can cause jumps in some cases.

**Comment by sonvister** [comment]
@turgayacar, when you use `await` you *are* executing your code in a synchronous manner... your code is waiting for the `Task` to complete before continuing (*without blocking a thread*). You can remove the `await` and let your code continue after the asynchronous `Task` has started, then await the `Task` later or combine it with other tasks and wait for them all (*many options*).

The recvWindow value determines the window of time a request is valid in milliseconds (*default 5000*). A value of 0 is ignored because that would essentially ensure all requests are aborted.

If you want to chain tasks, then you might try `ContinueWith()`.

**Comment by turgayacar** [comment]
Hi im solved.
type this code.  ".ConfigureAwait(true).GetAwaiter().GetResult()" end method. 
wait stay debuging and not run other codes. I win :)
