### ISSUE TITLE
Aggregate Trade Stream, Trade Stream or Ticker Stream

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#43]
If you simply wanted to get price changes of an asset (i.e. when a change in price is seen for an asset on the exchange the stream get's a message) which of the three streams would be the best to use?

**Comment by sonvister** [comment]
@rakewell here are some resources....

API information: [Binance Official Documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md)
API questions: [Binance API Telegram](https://t.me/binance_api_english)

**Comment by sonvister** [comment]
@rakewell, @Nucs, and @turgayacar (since this question is related to #26) if we define current price as the last trade price (*as opposed to mid-market price*), which would be consistent with Binance UIs... and 'best' is the stream with the most efficient and up-to-date price data... I'd say **Aggregate Trade Stream**, since Trade Stream pushes extra data and Ticker Stream pushes every second.
