### ISSUE TITLE
BinanceApiKey sample file

### ISSUE THREAD

**Issue by fhunth** [sonvister/Binance#59]
Could you add a configuration sampe file with BinanceApiKey ?
Thanks

**Comment by sonvister** [comment]
@fhunth, the `BinanceConsoleApp` sample provides an example of using a JSON configuration file (appsettings.json) as a backup means of loading the API key and secret if not available from the .NET application user secrets. Since there is currently no Configuration dependent code in this library the format of the file and means of loading that data are entirely up to the application.

**Comment by fhunth** [comment]
Thanks a lot!
