### ISSUE TITLE
symbols 

### ISSUE THREAD

**Issue by benjaminthedonkey** [sonvister/Binance#6]
Hi, 

I'm getting exception : Symbol does not match assets (ETC != ETCBTC)  when doing the "symbols" command. I think this was  working before...  

Thanks

**Comment by sonvister** [comment]
*It was working before* :) ...Binance is now sending an incompatible/invalid symbol ('ETC') in their list of symbols.

This has been patched in the latest source/release v0.2.0-alpha.6.

**Comment by benjaminthedonkey** [comment]
@sonvister  thanks for this project.  It's pretty cool. I got the code and  play around for a little bit.  I end up adding a new attribute to the Symbol class.  I needed it to calculate  the correct  quantity for an order.  It's call  'stepSize' and it comes in the LOT_SIZE filter.  If you are interested I can submit a  push request.

**Comment by sonvister** [comment]
Thanks @benjaminthedonkey. I am glad my project is helpful and getting some use.

Regarding '**stepSize**', I am aware of it and chose not to include that as an additional property of Symbol since it *was* and *should* be the same as '**minQty**'. So, to avoid redundancy, I left it out since it didn't seem logical that they would ever differ. Perhaps when I get back around to implementing a more structured and complete `ExchangeInfo` I may refactor `Symbol`; certainly if they do take on different values. You could argue that the safer approach would be to add it assuming it will eventually be different (*and that may have been your thoughts*). But, I chose the minimalist approach (*hoping for a simpler API*) and will add on later if necessary.

Perhaps using `Symbol.BaseMinQuantity` will work in your case.

**Comment by benjaminthedonkey** [comment]
Understood . I'm sure you arrived to that conclusion ( that should be the same as 'minQty' ) based on your knowledge, but for someone new to the API ( like me ) this is not obvious. The API documentation clearly talks about stepSize to calculate the lot size.  I would add a comment to the code to clarify or perhaps add the property  stepSize to the class Symbol  and make it return minQty value for now.  Just some ideas. Thanks  again!

**Comment by sonvister** [comment]
Thanks for your feedback @benjaminthedonkey. I agree it was not clear that the values could be used interchangeably. I hope this second *and more complete* pass at integrating the exchange info into the `Symbol` object including the *currently* redundant increments (*step size and tick size*) is more useful and intuitive (0.2.0-alpha.9). I will be updating my documentation also.
