### ISSUE TITLE
Rest API not trading?

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#66]
Hey,
Was running my bot and when it tried to Cancel an order by its ID, it errored with the following:

Rest API trading is not enabled.
Error Code 2010
[BadRequest]: 'Bad Request' - Rest API trading is not enabled. (-2010)

This was trading on BTCUSDT.

I restarted my bot, and when it then tried placing a sell order, the sell order was recieved by binance and was placed, but the sell order request timed out, with no message or code returned from binance.

I recieved a phone call whilst trying to chase this down, but it appears to be working again now... Seems something weird may have happened momentarily with the API? Anything I should do to try and handle this situation?

**Comment by sonvister** [comment]
@pingu2k4, the request timeout sounds like similar network issues you have experienced where you have the recvWindow parameter and the `HttpClientTimeoutDefaultSeconds` option to allow for more time. If network issues are reoccurring, and not due to Binance, maybe consider running your application on a VM with a more reliable connection (*something close to Japan perhaps*). Regardless, if a timeout occurs, it may be a good strategy to verify if the order was placed (*using your client order ID*), same as with [504 errors](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md).

As for the REST API not trading issue, perhaps you could check the Symbol status (*after updating cache of Symbols*) to determine if the symbol is trading before placing an order. Or check the Binance system status to see if maintenance is in progress. Here is the [official API error information](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md). If that doesn't help, perhaps you can ask about the error on the official API Telegram.

**Comment by sonvister** [comment]
@pingu2k4, based on this and #64, I've updated the [exception handling docs](https://github.com/sonvister/Binance/wiki/Exception-Handling). Can you confirm if your sell order timeout returned the same `TaskCanceledException` (*or something else that should be in the docs*)?

**Comment by pingu2k4** [comment]
Never had this happen again, think it was something with the exchange, as a few others from the Telegram channel noticed the same thing happen at the same time. Haven't been able to test the exception handling stuff, but think its worthy of closing.
