### ISSUE TITLE
Question: What validations to perform before placing a market order?

### ISSUE THREAD

**Issue by betimd** [sonvister/Binance#78]
I'm placing a market order (say XRPETH, 20, SELL) and sometimes I'm getting "Error happened while making order to Binance. Filter failure: **LOT_SIZE**", sometimes succeed. 
So, is there any kind of checks to perform before placing a market order?

**Comment by sonvister** [comment]
@betimd, there are a couple of `ClientOrder` extension methods available: `IsValid()` and `Validate()`. The former returns a `bool` result and the later throws an exception with a message. Both use the cached `Symbol` information to determine, among other things, if the `ClientOrder.Quantity` will pass the 'LOT_SIZE' filter for the symbol. The static asset/symbol information is only as recent as the latest build, but you can update them using `Symbol.UpdateCacheAsync()`.

Reference: [Official Binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters)

**Comment by betimd** [comment]
@sonvister is there any way to "format" quantity of a symbol before making order? Because if I'm having a market order TRXBTC, and I send say 1000.98 I get exception (LOT_SIZE). Thought, let me remove decimals and round a full number and it worked. But on the same time I cannot do this with BTC, while value of BTC I have say it's ~0.1982, so the former rounding doesn't work while it gives me 0. So, is there any way to have a proper qty for a pair?

**Comment by sonvister** [comment]
@betimd, for that there are 3 extension methods on `InclusiveRange` or `symbol.Quantity`: `GetUpperValidValue`, `GetValidValue`, and `GetLowerValidValue`. The comments should help explain how each work if the names aren't enough. For more info, the source code is `InclusiveRangeExtensions.cs`.

**Comment by betimd** [comment]
@sonvister very helpful. Thnx a lot. What would be the best updating rate of symbol caches? In hours, days, weeks. I mean I want to have serialized locally and not ping Binance every time I check any amount of price if it's correct.

**Comment by sonvister** [comment]
@betimd, I do not know what is best. I can say this data doesn't change very frequently and most of the changes are additional symbols. At a minimum, I would update when the application starts (*as updates to this library will become less frequent*). Serializing seems unnecessary, since I can't imagine a use case where an application is starting and stopping so frequently. Beyond that, I would again update if the 'LOT_SIZE' or similar filter failure occurs during order placement after validation passes. Also, some changes may not cause an error, but not give you the best result. So, a regular update should also occur which is application dependent. The [exchange info](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information) rate limit weight is 1, so conceivably you *could* refresh the cache frequently.
