### ISSUE TITLE
[Suggestion] Use the String Interning for Candlestick.Symbol property.

### ISSUE THREAD

**Issue by sguryev** [sonvister/Binance#84]
I'm making a lot of REST API calls as well as WebSocket connections. dotMemory says that I can optimize memory by using String Interning for frequently used string values (just imagine - 1000 candlesticks with the same symbol `ETHBTC` x intervals) 
![image](https://user-images.githubusercontent.com/6978458/38438614-a94e4f34-39e3-11e8-8067-38568c32103f.png)

Article to read: https://blog.jetbrains.com/dotnet/2015/02/12/string-interning-effective-memory-management-with-dotmemory/

**Comment by sguryev** [comment]
Actually it would be awesome to use the `string.Intern()` as much as possible

**Comment by sonvister** [comment]
@sguryev, good suggestion. I've added string interning to the assets and symbols. Feel free to close this issue when you can verify the memory usage is optimized with latest code or the next release. Thanks.

**Comment by sguryev** [comment]
Hmmm... I have left a couple of comments. They says that literals are interned by default. Since you have all the possible symbols as literals in the Cache they should be interned in all other places: (Binance API response deserialization, etc). Not sure if it work for the Dictionary keys though.

**Comment by sguryev** [comment]
You have the code generation there. Is it design time generator?

**Comment by sonvister** [comment]
@sguryev, your're right about string literals; I've corrected. Thanks.

Yes, the known symbols will be interned by the static `Cache` declaration. All other changes (*where strings are modified/generated*) remain since we also want to handle new assets and symbols (*created when the cache is updated*), which is also why I didn't use `IsInterned`.

The `BinanceCodeGenerator` program is used to get the latest assets and symbols and generate the `Asset.cs` and `Symbol.cs` files. Had that been more tedious to implement I may have looked up automatic interning of string literals beforehand 😉

**Comment by sguryev** [comment]
I think we can close the issue now. Thank you!
