### ISSUE TITLE
Issue with ToCandlestickInterval() method

### ISSUE THREAD

**Issue by sguryev** [sonvister/Binance#86]
Hi @sonvister ,

I worked around the `ToCandlestickInterval` extension and have noticed this line:
https://github.com/sonvister/Binance/blob/a7277db9c9b9a05b4daf51fb6f8e4a107f7f0595/src/Binance/Extensions/StringExtensions.cs#L59

I didn't test but I'm 99% sure that after making `s.Trim().ToLower()` you will not me able get `case "1M"` and the main problem - it will go to the `case "1m"`. What do you think?

**Comment by sguryev** [comment]
Hmmmm, not sure if it affects the subscriptions. I remember the #82 issue related to the subscription and `6h` interval. So I guess that it should affect it. Does it mean that on May 1st it should return `1M` candle with monthly values but to the `1m` interval?

**Comment by sonvister** [comment]
@sguryev, you are correct. The `ToCandlestickInterval` method `ToLower()` would prevent the `"1M"` match. 🤦‍♂️

**Comment by sguryev** [comment]
What about my assumption about affected logic?

**Comment by sonvister** [comment]
The #82 issue was just the missing "6h" case. Here, the `ToLower()` was added only so the method would be case insensitive (*obviously overlooking the "1M" at the time*). Could you elaborate on 'affected logic'?

**Comment by sguryev** [comment]
I'm collecting the candles using WebSocket to the custom store. I'm concerned about the data messing which this bug can lead to. My assumption that `1M` subscription will be proceeded as `1m` with this bug. And `1M` candle will be recognized as `1m`. Am I correct?

**Comment by sonvister** [comment]
Before 0.2.0-beta3, using `ToCandlestickInterval()` with "1M" would return `CandlestickInterval.Minute` instead of `CandlestickInterval.Month` and return the wrong data regardless (*so, @sguryev,  you likely have the wrong monthly data*).

If subscribing or polling with `CandlestickInterval` values (*not converting from string*) the data would be as expected, but each returned `Candlestick` would have the wrong `CandlestickInterval` for monthly data (*since `ToCandlestickInterval()` is used when deserializing candlestick data*).

If using the `IBinanceApi.GetCandlesticksAsync()` extension with `string` parameter you will also get the wrong data for "1M" because of the conversion from string to `CandlestickInterval`.

With 0.2.0-beta3, anyone previously using uppercase strings with `ToCandlestickInterval()` or `GetCandlesticksAsync()` (*low probability scenario*) will now get errors or `CandlestickInterval.Month` instead of `CandlestickInterval.Minute`.
