### ISSUE TITLE
Call hangs in DefaultWebSocketClient.StreamAsync: Web socket connecting... 

### ISSUE THREAD

**Issue by rcbapb** [sonvister/Binance#88]
Hi, 

I am using your library to download 1 minute data continuously for further analysis. This works very well, but every few days, the download stops and I need to restart and as a result I miss data.

In the log file I see this:
DefaultWebSocketClient.StreamAsync: Web socket connecting... 
but it is never followed by a 
DefaultWebSocketClient.OnOpen: Web Socket OPEN. 
like in the normal situation.

It just seems to get stuck in this call. Is there a way to use a timeout / retry mechanism, so I don't need to manually monitor whether or not the application is still running?

Thanks for your excellent work,
Peter

**Comment by sonvister** [comment]
@rcbapb, to have a websocket connection timeout you would need to pass a `CancellationToken` with `TimeSpan` to the `StreamAsync(token)` method.

```C#
var cts = new CancellationTokenSource(TimeSpan);
```

The automatic stream control won't do this for you. You would need to control the `BinanceWebSocketStream` directly, like the advanced examples but with your own retry controller implementation that uses a cancellation token source with timeout (*above*).

I may consider implementing something like this in the not so soon future; I'm not taking on a new features with 0.2.0. Also, the issue would need to be reproduced and shown that using a connection timeout to abort and reconnect proves to be a solution (*that would take some time*). Besides, if the underlying issue is network related or otherwise external to the software then, I imagine, a reconnect attempt will just hang too.

If your application just needs notification when this situation occurs, perhaps create a timer on the `IWebSocketClient.Close` event (*and maybe at application startup too*) that gets disposed on the `Open` event. The timer action could then restore the application from a higher level.

**Comment by rcbapb** [comment]
@sonvister Thank you for your reply. I could use the CancellationToken approach to simulate a cancelled stream, but when it happened by itself, I never got the IWebSocket.Close event. The call to connect was just hanging forever. I'd probably need some external application or a separate thread that will terminate the connection a try again.

**Comment by sonvister** [comment]
@rcbapb, yes, you mentioned that `Connect()` did not complete/return and there was no `Close` event. BTW, if `Connect()` is cancelled you should not get either an `Open` or `Close` event.

The 'separate thread' would be the timer action I suggested that you would initialize at application startup and/or with the `Close` event during a reconnect attempt (*I wasn't sure which to recommend first before as you didn't specify whether there was a preceding `Close` event*).

Also, if this is not a reoccurring issue (*as it now sounds like with your last comment*), then I would not worry about it.
