### ISSUE TITLE
please update new pairs. For example BCN-BTC...etc

### ISSUE THREAD

**Issue by phamanhtho** [sonvister/Binance#93]
please update new pairs. For example BCN-BTC...etc Thanks

**Comment by sonvister** [comment]
...[it is not a goal of this project to create a new release just to update the static assets and symbols](https://github.com/sonvister/Binance/wiki) since the static assets and symbols are there for convenience, not necessity.

The only way to update these is with a new build. If necessary for your application, the source code is available to add the pairs by running `BinanceCodeGenerator` tool and use a local NuGet build of the library instead of the publicly available build.

**Comment by sonvister** [comment]
One possibility (*made available with the latest changes*) would be to add all known pairs including those that Binance has not listed yet and they would return `null` until they are listed (*and the cache is updated*), but that may be more confusing than helpful (*not liking that idea*).

**Comment by sonvister** [comment]
Also, an application could maintain their own `BinanceSymbol` class with static properties that reference `Binance.Symbol.Cache`. I am considering modifying the tool to generate a partial class that would be available to include in applications (*not part of the library*).

Then, anyone using the static assets and symbols would need to update their code (`Symbol` -> `BinanceSymbol`).

**Comment by sonvister** [comment]
[**0.2.0-beta5**](https://github.com/sonvister/Binance/releases/tag/v0.2.0-beta5) includes BCN_BTC.
