### ISSUE TITLE
How do I determine the remaining Requests/Orders available per time period?

### ISSUE THREAD

**Issue by Psyral** [sonvister/Binance#95]
And is it possible to also get the rate limit weights for a particular Request/Order?

**Comment by sonvister** [comment]
@Psyral, with `IApiRateLimiter` and `IRateLimiter`, there is no way to determine the remaining count (`_count - _timestamps.Count` *...not including weight*) before calls are delayed. Also, this is not something I would likely add since the purpose of the rate limiters is to prevent applications from needing to deal with the request rate limitations (*and needing this information*). It may be helpful to understand why you want access to that information.

The only way to get the actual weights at run-time is with `IBinanceApi.GetRateLimitInfoAsync()`. The rate limit weights used by this library are hard-coded in `BinanceHttpClientExtensions`.

**Comment by Psyral** [comment]
Understood. It was more for GUI display/informational purposes. Not a needed feature since you provide rate limiting services automatically.  Thanks for the response.
